(function () {
  "use strict";

  const SERVICES = ["Sunday Divine Service", "Communion Service", "Thanksgiving Service", "Special Programme"];
  const state = { client: null, userId: null, permissions: [], members: [], events: [], occasions: [], participants: [], selectedOccasionId: null, editingParticipantId: null, registerSearch: "", rosterSearch: "", initialized: false, bound: false, loading: false };
  const $ = (selector, scope = document) => scope.querySelector(selector);
  const $$ = (selector, scope = document) => Array.from(scope.querySelectorAll(selector));
  const esc = (value = "") => String(value).replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]);
  const can = permission => state.permissions.includes(permission);
  const notify = (message, type) => window.PCGApp?.toast(message, type);
  const refreshIcons = () => window.lucide?.createIcons({ attrs: { "stroke-width": 1.8 } });
  const todayIso = () => new Date().toISOString().slice(0, 10);
  const dateFromIso = value => new Date(`${value}T00:00:00`);
  const dateFormat = new Intl.DateTimeFormat("en-GH", { day: "numeric", month: "short", year: "numeric" });
  const longDateFormat = new Intl.DateTimeFormat("en-GH", { day: "numeric", month: "long", year: "numeric" });
  const formatDate = value => value ? dateFormat.format(dateFromIso(value)) : "—";
  const relation = (record, key) => Array.isArray(record?.[key]) ? record[key][0] : record?.[key];
  const fullName = member => `${member?.first_name || ""} ${member?.last_name || ""}`.trim() || "Unnamed member";
  const isCurrentMember = member => ["Active", "Transferred In"].includes(member?.status);
  const normalizedPersonName = value => String(value || "").trim().replace(/\s+/g, " ").toLowerCase();
  const normalizedGroup = value => String(value || "").toLowerCase().replace(/[^a-z]+/g, "");
  const isExcludedGroup = value => ["childrenservice", "junioryouth", "junioryouthjy"].includes(normalizedGroup(value));

  function memberEligibility(member, occasionDate = todayIso()) {
    const targetDate = dateFromIso(occasionDate);
    const groups = window.GenerationalGroups?.getGroups?.() || [];
    const classification = window.GenerationalGroups?.classify(member, groups, targetDate) || { code: "rules-unavailable", group: null };
    const groupName = classification.group?.name || "Not classified";
    const excluded = isExcludedGroup(groupName);
    const activeChurchMember = isCurrentMember(member);
    const adultGroupEligible = classification.code === "matched" && !excluded;
    const communicant = member?.communicant_status === "Communicant";
    const reason = !activeChurchMember
      ? "Only current Resurrection members can be recorded here. Transferred Out and Deceased records remain historical."
      : excluded
      ? `${groupName} members do not partake in Communion.`
      : classification.code !== "matched"
        ? "This member has no valid adult generational group for the Communion date."
        : !communicant
          ? "This member is recorded as Non-Communicant."
          : "Eligible Communicant";
    return { eligible: activeChurchMember && adultGroupEligible && communicant, activeChurchMember, adultGroupEligible, communicant, groupName, reason, classification };
  }

  function mount() {
    const root = $("#communionModuleRoot");
    if (!root || root.dataset.mounted) return;
    root.dataset.mounted = "true";
    root.innerHTML = `
      <div class="page-heading communion-heading"><div><p class="breadcrumb">Home <i data-lucide="chevron-right"></i> Communion</p><h2>Communion records</h2><p>Maintain Communion occasions and the people who actually partook. Attendance remains a separate church record.</p></div><button class="primary-btn" id="communionPrimaryAction" type="button" data-requires="communion.manage"><i data-lucide="plus"></i> New Communion Occasion</button></div>
      <div class="communion-message" id="communionMessage" hidden></div><div id="communionContent"></div>

      <dialog id="communionOccasionDialog" class="communion-dialog"><form id="communionOccasionForm">
        <input type="hidden" name="occasion_id"><div class="dialog-header"><div><p class="eyebrow">COMMUNION OCCASION</p><h3 id="communionOccasionDialogTitle">New Communion Occasion</h3></div><button class="icon-btn" type="button" data-close-communion="communionOccasionDialog" aria-label="Close"><i data-lucide="x"></i></button></div>
        <div class="dialog-body"><label>Communion date<input name="communion_date" type="date" required></label><label>Occasion / service<input name="service_name" list="communionServices" maxlength="120" required placeholder="e.g. Sunday Divine Service"><datalist id="communionServices">${SERVICES.map(value => `<option value="${esc(value)}">`).join("")}</datalist></label><label>Scheduled programme (optional)<select name="event_id"><option value="">No linked programme</option></select></label><label>Location<input name="location" maxlength="160" placeholder="e.g. Main Sanctuary"></label><label class="full">Presiding Minister / Minister<input name="presiding_minister" maxlength="160" required></label><label class="full">Notes<textarea name="notes" maxlength="2000" placeholder="Communion record notes…"></textarea></label><p class="full communion-form-error" id="communionOccasionError" hidden></p></div>
        <div class="dialog-footer"><button class="secondary-btn" type="button" data-close-communion="communionOccasionDialog">Cancel</button><button class="primary-btn" type="submit">Save occasion</button></div>
      </form></dialog>

      <dialog id="communionParticipantDialog" class="communion-dialog communion-participant-dialog"><form id="communionParticipantForm">
        <input type="hidden" name="participant_id"><input type="hidden" name="occasion_id"><input type="hidden" name="member_id">
        <div class="dialog-header"><div><p class="eyebrow">COMMUNION REGISTER</p><h3 id="communionParticipantDialogTitle">Add Communion Participant</h3></div><button class="icon-btn" type="button" data-close-communion="communionParticipantDialog" aria-label="Close"><i data-lucide="x"></i></button></div>
        <div class="dialog-body">
          <label>Person type<select name="person_type"><option>Member</option><option>Visitor</option></select></label>
          <div class="full communion-member-picker" id="communionMemberPicker"><label>Find registered member<input id="communionMemberSearch" type="search" autocomplete="off" placeholder="Search by name, phone, email, or group"></label><div id="communionMemberResults" class="communion-member-results"></div><div id="communionSelectedMember" class="communion-selected-member" hidden></div></div>
          <div class="full communion-visitor-fields" id="communionVisitorFields" hidden><label>Visitor / non-member full name<input name="visitor_name" maxlength="160"></label><label>Gender<select name="visitor_gender"><option>Female</option><option>Male</option></select></label><label>Communicant status<select name="visitor_communicant_status"><option>Communicant</option><option>Non-Communicant</option><option>Unknown</option></select></label></div>
          <div class="full communion-eligibility-preview" id="communionEligibilityPreview"></div>
          <label class="full communion-partook-field"><input name="partook" type="checkbox" checked><span><strong>Partook in Communion</strong><small>Eligibility and actual participation are recorded separately.</small></span></label>
          <label class="full">Notes<textarea name="notes" maxlength="1000" placeholder="Optional register notes…"></textarea></label><p class="full communion-form-error" id="communionParticipantError" hidden></p>
        </div><div class="dialog-footer"><button class="secondary-btn" type="button" data-close-communion="communionParticipantDialog">Cancel</button><button class="primary-btn" id="communionParticipantSubmit" type="submit">Record as Partaken</button></div>
      </form></dialog>`;
  }

  function communionStats(source = []) {
    const records = source.filter(item => item.partook);
    const groups = new Map();
    records.filter(item => item.person_type === "Member").forEach(item => groups.set(item.generational_group_snapshot, (groups.get(item.generational_group_snapshot) || 0) + 1));
    return { total: records.length, male: records.filter(item => item.gender_snapshot === "Male").length, female: records.filter(item => item.gender_snapshot === "Female").length, members: records.filter(item => item.person_type === "Member").length, visitors: records.filter(item => item.person_type === "Visitor").length, groups };
  }

  function statsFor(occasionId) { return communionStats(state.participants.filter(item => item.occasion_id === occasionId)); }

  function metric(label, value, note, icon, tone = "blue") {
    return `<article class="communion-metric ${tone}"><div><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div><i data-lucide="${icon}"></i></article>`;
  }

  function sortedOccasions() { return state.occasions.slice().sort((a, b) => b.communion_date.localeCompare(a.communion_date) || b.created_at.localeCompare(a.created_at)); }

  function trendMarkup() {
    const rows = sortedOccasions().slice(0, 12).reverse().map(item => ({ item, value: statsFor(item.id).total }));
    const max = Math.max(...rows.map(row => row.value), 1);
    const first = rows[0]?.value || 0; const last = rows.at(-1)?.value || 0; const direction = last > first ? "Increasing" : last < first ? "Decreasing" : "Stable";
    return `<article class="card communion-trend-card"><div class="communion-card-heading"><div><p class="eyebrow">COMMUNION PARTICIPATION TREND</p><h3>Recorded participants over time</h3><p>Counts only register entries explicitly marked Partook.</p></div><span class="communion-direction ${direction.toLowerCase()}"><i data-lucide="${direction === "Increasing" ? "trending-up" : direction === "Decreasing" ? "trending-down" : "minus"}"></i>${direction}</span></div><div class="communion-trend" role="img" aria-label="Communion participation trend">${rows.length ? rows.map(row => `<div title="${esc(row.item.service_name)} · ${formatDate(row.item.communion_date)} · ${row.value} participants"><strong>${row.value}</strong><span><i style="height:${row.value ? Math.max(8, row.value / max * 100) : 2}%"></i></span><small>${esc(formatDate(row.item.communion_date))}</small></div>`).join("") : `<div class="communion-empty"><i data-lucide="chart-no-axes-column"></i><p>No Communion participation records yet.</p></div>`}</div></article>`;
  }

  function dashboardMarkup() {
    const latest = sortedOccasions()[0]; const latestStats = latest ? statsFor(latest.id) : { total: 0, male: 0, female: 0, members: 0, visitors: 0 };
    const recordingCallout = can("communion.manage") ? `<article class="communion-recording-callout"><div class="communion-recording-callout-icon"><i data-lucide="book-user"></i></div><div><p class="eyebrow">INDIVIDUAL COMMUNION PARTICIPATION</p><h3>${latest ? "Ready to record who partook?" : "Create a Communion occasion first"}</h3><p>${latest ? `Open <strong>${esc(latest.service_name)}</strong> for ${esc(formatDate(latest.communion_date))}, search for an eligible communicant, and record the member as partaken.` : "Each person's participation is saved inside a specific Communion occasion and date."}</p></div><div class="communion-recording-callout-actions">${latest ? `<button class="primary-btn" type="button" data-communion-register="${latest.id}"><i data-lucide="users-round"></i> Record participants</button>` : ""}<button class="secondary-btn" type="button" data-communion-open-occasion><i data-lucide="plus"></i> New Communion occasion</button></div></article>` : `<article class="communion-recording-callout read-only"><div class="communion-recording-callout-icon"><i data-lucide="lock-keyhole"></i></div><div><p class="eyebrow">READ-ONLY ACCESS</p><h3>Participation recording is unavailable for this role</h3><p>An administrator must grant the <strong>Manage Communion</strong> permission before this account can add, edit, or remove participants.</p></div></article>`;
    return `<div class="communion-stat-grid">${metric("Latest Communion", latest ? formatDate(latest.communion_date) : "—", latest?.service_name || "No occasion recorded", "calendar-heart", "blue")}${metric("Participants", latestStats.total, "Actually partook", "church", "green")}${metric("Male", latestStats.male, "Latest Communion", "person-standing", "blue")}${metric("Female", latestStats.female, "Latest Communion", "person-standing", "red")}${metric("Registered Members", latestStats.members, "Who partook", "users", "green")}${metric("Eligible Visitors", latestStats.visitors, "Who partook", "user-plus", "orange")}</div>${recordingCallout}<div class="communion-dashboard-grid">${trendMarkup()}<article class="card communion-principle-card"><p class="eyebrow">RECORD PRINCIPLE</p><h3>Attendance ≠ Communion Participation</h3><p>People are counted here only when an authorized user records their Communion participation. Service attendance is never copied automatically.</p><ul><li>Children Service: not eligible</li><li>Junior Youth (JY): not eligible</li><li>Adult members: Communicant status required</li><li>Visitors: communicant eligibility required</li></ul></article></div>${occasionTableMarkup()}`;
  }

  function occasionTableMarkup() {
    const rows = sortedOccasions();
    const body = rows.length ? rows.map(item => {
      const stats = statsFor(item.id);
      const registerLabel = can("communion.manage") ? "Record participants" : "View register";
      return `<tr><td>${formatDate(item.communion_date)}</td><td><button class="communion-link" type="button" data-communion-register="${item.id}">${esc(item.service_name)}</button><small>${esc(item.notes || "No notes")}</small></td><td><strong>${esc(item.presiding_minister)}</strong><small>${esc(item.location || "Location not recorded")}</small></td><td><strong>${stats.total}</strong></td><td>${stats.members}</td><td>${stats.visitors}</td><td>${esc(item.created_by_name || "Church officer")}</td><td><div class="row-actions communion-occasion-actions"><button class="secondary-btn communion-open-register-action" type="button" data-communion-register="${item.id}"><i data-lucide="book-open-check"></i> ${registerLabel}</button>${can("communion.manage") ? `<button class="icon-btn" type="button" data-communion-edit-occasion="${item.id}" title="Edit occasion"><i data-lucide="pencil"></i></button><button class="icon-btn delete" type="button" data-communion-delete-occasion="${item.id}" title="Delete occasion"><i data-lucide="trash-2"></i></button>` : ""}</div></td></tr>`;
    }).join("") : `<tr><td colspan="8"><div class="communion-empty"><i data-lucide="church"></i><p>No Communion occasions have been recorded.</p>${can("communion.manage") ? `<button class="primary-btn" type="button" data-communion-open-occasion><i data-lucide="plus"></i> Create the first Communion occasion</button>` : ""}</div></td></tr>`;
    return `<article class="card communion-record-card"><div class="communion-card-heading"><div><p class="eyebrow">COMMUNION OCCASIONS</p><h3>Select an occasion to record participants</h3><p>Participation is recorded inside the register for the exact Communion service and date.</p></div>${can("communion.manage") ? `<button class="secondary-btn" type="button" data-communion-open-occasion><i data-lucide="plus"></i> New occasion</button>` : ""}</div><div class="table-scroll"><table class="communion-table"><thead><tr><th>Date</th><th>Occasion / Service</th><th>Minister / Location</th><th>Participants</th><th>Members</th><th>Visitors</th><th>Recorded by</th><th>Register</th></tr></thead><tbody>${body}</tbody></table></div></article>`;
  }

  function participantName(item) { return item.person_type === "Member" ? fullName(relation(item, "members") || state.members.find(member => member.id === item.member_id)) : item.visitor_name; }

  function memberRosterMarkup(occasion) {
    const query = state.rosterSearch.trim().toLowerCase();
    const members = state.members.filter(isCurrentMember).filter(member => !query || [fullName(member), member.phone, member.email, member.group_name, member.communicant_status].join(" ").toLowerCase().includes(query)).sort((a, b) => fullName(a).localeCompare(fullName(b)));
    return `<article class="card communion-roster-card"><div class="communion-card-heading"><div><p class="eyebrow">INDIVIDUAL COMMUNION PARTICIPATION</p><h3>Record individual participants</h3><p>Eligibility is calculated for ${esc(formatDate(occasion.communion_date))}. Ineligible active members remain visible with the reason they cannot partake.</p></div></div><div class="communion-roster-toolbar"><label><i data-lucide="search"></i><input id="communionRosterSearch" type="search" placeholder="Search the member list…" value="${esc(state.rosterSearch)}"></label><span>${members.length} member${members.length === 1 ? "" : "s"}</span></div><div class="table-scroll"><table class="communion-table communion-roster-table"><thead><tr><th>Member</th><th>Gender</th><th>Age-based Group</th><th>Communicant Status</th><th>Eligibility</th><th>Register Record</th><th></th></tr></thead><tbody>${members.length ? members.map(member => { const eligibility = memberEligibility(member, occasion.communion_date); const record = state.participants.find(item => item.occasion_id === occasion.id && item.member_id === member.id); return `<tr><td><strong>${esc(fullName(member))}</strong><small>${esc(member.phone || member.email || member.status)}</small></td><td>${esc(member.gender)}</td><td>${esc(eligibility.groupName)}</td><td><span class="communion-status ${(member.communicant_status || "Non-Communicant").toLowerCase().replaceAll("-", "")}">${esc(member.communicant_status || "Non-Communicant")}</span></td><td><span class="communion-eligibility-badge ${eligibility.eligible ? "eligible" : "ineligible"}"><i data-lucide="${eligibility.eligible ? "badge-check" : "circle-alert"}"></i>${esc(eligibility.eligible ? "Eligible" : eligibility.reason)}</span></td><td>${record ? `<span class="communion-partook ${record.partook ? "yes" : "no"}"><i data-lucide="${record.partook ? "check" : "minus"}"></i>${record.partook ? "Partook" : "Did not partake"}</span>` : `<span class="communion-not-recorded">Not recorded</span>`}</td><td>${can("communion.manage") ? record ? `<button class="secondary-btn communion-record-action" type="button" data-communion-edit-participant="${record.id}"><i data-lucide="pencil"></i> Edit</button>` : `<button class="primary-btn communion-record-action" type="button" data-communion-record-member="${member.id}" ${eligibility.eligible ? "" : "disabled"}><i data-lucide="book-user"></i> Record</button>` : ""}</td></tr>`; }).join("") : `<tr><td colspan="7"><div class="communion-empty"><i data-lucide="search-x"></i><p>No active members match this search.</p></div></td></tr>`}</tbody></table></div></article>`;
  }

  function registerMarkup(occasion) {
    const stats = statsFor(occasion.id); const search = state.registerSearch.toLowerCase();
    const records = state.participants.filter(item => item.occasion_id === occasion.id).filter(item => !search || [participantName(item), item.person_type, item.generational_group_snapshot, item.communicant_status, item.notes].join(" ").toLowerCase().includes(search)).sort((a, b) => participantName(a).localeCompare(participantName(b)));
    const groupBreakdown = Array.from(stats.groups).sort((a, b) => b[1] - a[1]).map(([name, count]) => `<span>${esc(name)} <b>${count}</b></span>`).join("");
    const entryPanel = can("communion.manage") ? `<article class="communion-entry-panel"><div class="communion-entry-panel-copy"><span class="communion-entry-step">1</span><div><p class="eyebrow">INDIVIDUAL COMMUNION PARTICIPATION</p><h3>Record a person who partook</h3><p>Search for an eligible communicant member, or enter an eligible visitor separately. The entry will be saved to this service.</p></div></div><div class="communion-entry-panel-actions"><button class="primary-btn" type="button" data-communion-add="Member"><i data-lucide="search"></i> Record member as partaken</button><button class="secondary-btn" type="button" data-communion-add="Visitor"><i data-lucide="user-plus"></i> Record visitor / non-member</button></div></article>` : `<article class="communion-entry-panel read-only"><div class="communion-entry-panel-copy"><span class="communion-entry-step"><i data-lucide="lock-keyhole"></i></span><div><p class="eyebrow">READ-ONLY ACCESS</p><h3>You cannot record participants with this role</h3><p>Ask a Super Administrator to grant the Manage Communion permission.</p></div></div></article>`;
    return `<button class="communion-back" type="button" data-communion-dashboard><i data-lucide="arrow-left"></i> Communion overview</button><div class="communion-register-heading"><div><p class="eyebrow">COMMUNION REGISTER</p><h2>${esc(occasion.service_name)} — ${esc(longDateFormat.format(dateFromIso(occasion.communion_date)))}</h2><p>${esc(occasion.presiding_minister)}${occasion.location ? ` · ${esc(occasion.location)}` : ""}</p></div></div>${entryPanel}<div class="communion-register-metrics">${metric("Total Participants", stats.total, "Marked Partook", "church", "green")}${metric("Male", stats.male, "Actual participants", "person-standing", "blue")}${metric("Female", stats.female, "Actual participants", "person-standing", "red")}${metric("Members", stats.members, "Registered members", "users", "blue")}${metric("Eligible Visitors", stats.visitors, "Visitor / non-member", "user-plus", "orange")}</div>${groupBreakdown ? `<div class="communion-group-breakdown"><strong>Adult group breakdown</strong>${groupBreakdown}</div>` : ""}${memberRosterMarkup(occasion)}<article class="card communion-record-card"><div class="communion-card-heading"><div><p class="eyebrow">RECORDED PARTICIPATION</p><h3>Communion Register entries</h3></div></div><div class="communion-register-toolbar"><label><i data-lucide="search"></i><input id="communionRegisterSearch" type="search" placeholder="Search recorded participation…" value="${esc(search)}"></label><span>${records.length} register entr${records.length === 1 ? "y" : "ies"}</span></div><div class="table-scroll"><table class="communion-table"><thead><tr><th>No.</th><th>Person</th><th>Type</th><th>Group</th><th>Communicant Status</th><th>Partook</th><th>Notes</th><th></th></tr></thead><tbody>${records.length ? records.map((item, index) => `<tr><td>${index + 1}</td><td><strong>${esc(participantName(item))}</strong><small>${esc(item.gender_snapshot)}</small></td><td>${esc(item.person_type)}</td><td>${esc(item.generational_group_snapshot)}</td><td><span class="communion-status ${item.communicant_status.toLowerCase().replaceAll("-", "")}">${esc(item.communicant_status)}</span></td><td><span class="communion-partook ${item.partook ? "yes" : "no"}"><i data-lucide="${item.partook ? "check" : "minus"}"></i>${item.partook ? "Yes" : "No"}</span></td><td>${esc(item.notes || "—")}</td><td>${can("communion.manage") ? `<div class="row-actions"><button class="icon-btn" type="button" data-communion-edit-participant="${item.id}" title="Edit register entry"><i data-lucide="pencil"></i></button><button class="icon-btn delete" type="button" data-communion-delete-participant="${item.id}" title="Remove register entry"><i data-lucide="trash-2"></i></button></div>` : ""}</td></tr>`).join("") : `<tr><td colspan="8"><div class="communion-empty"><i data-lucide="book-open-check"></i><p>No one has been recorded for this Communion service yet.</p></div></td></tr>`}</tbody></table></div></article>`;
  }

  function render() {
    const content = $("#communionContent"); if (!content) return;
    const primary = $("#communionPrimaryAction"); if (primary) primary.hidden = !can("communion.manage") || Boolean(state.selectedOccasionId);
    if (!can("communion.view") && state.initialized) { content.innerHTML = `<article class="card communion-empty"><i data-lucide="shield-alert"></i><p>Your role does not provide access to Communion records.</p></article>`; refreshIcons(); return; }
    if (state.loading) { content.innerHTML = `<div class="communion-loading"><i data-lucide="loader-circle"></i><p>Loading Communion records…</p></div>`; refreshIcons(); return; }
    const occasion = state.occasions.find(item => item.id === state.selectedOccasionId);
    if (state.selectedOccasionId && !occasion) state.selectedOccasionId = null;
    content.innerHTML = occasion ? registerMarkup(occasion) : dashboardMarkup(); refreshIcons();
  }

  function formError(selector, message = "") { const node = $(selector); if (!node) return; node.hidden = !message; node.textContent = message; }

  function openOccasion(record = null) {
    if (!can("communion.manage")) return notify("You do not have permission to manage Communion records.", "error");
    const form = $("#communionOccasionForm"); form.reset(); formError("#communionOccasionError");
    form.elements.event_id.innerHTML = `<option value="">No linked programme</option>${state.events.slice().sort((a, b) => b.event_date.localeCompare(a.event_date)).map(event => `<option value="${event.id}">${esc(event.title)} · ${formatDate(event.event_date)}</option>`).join("")}`;
    form.elements.occasion_id.value = record?.id || ""; form.elements.communion_date.value = record?.communion_date || todayIso(); form.elements.service_name.value = record?.service_name || "Communion Service"; form.elements.event_id.value = record?.event_id || ""; form.elements.location.value = record?.location || "Main Sanctuary"; form.elements.presiding_minister.value = record?.presiding_minister || ""; form.elements.notes.value = record?.notes || "";
    $("#communionOccasionDialogTitle").textContent = record ? "Edit Communion Occasion" : "New Communion Occasion"; $("#communionOccasionDialog").showModal(); refreshIcons();
  }

  function renderMemberResults(search = "") {
    const form = $("#communionParticipantForm"); const occasion = state.occasions.find(item => item.id === form.elements.occasion_id.value); const query = search.trim().toLowerCase();
    const records = state.members.map(member => ({ member, eligibility: memberEligibility(member, occasion?.communion_date) })).filter(item => item.eligibility.eligible).filter(item => !query || [fullName(item.member), item.member.phone, item.member.email, item.member.group_name].join(" ").toLowerCase().includes(query)).slice(0, 30);
    $("#communionMemberResults").innerHTML = records.length ? records.map(({ member, eligibility }) => { const alreadyRegistered = state.participants.some(item => item.occasion_id === occasion?.id && item.member_id === member.id && item.id !== state.editingParticipantId); const explanation = alreadyRegistered ? "Already in this Communion Register" : "Eligible Communicant"; return `<button type="button" data-communion-select-member="${member.id}" ${alreadyRegistered ? "disabled" : ""}><span><strong>${esc(fullName(member))}</strong><small>${esc(eligibility.groupName)} · Communicant</small></span><em class="${alreadyRegistered ? "ineligible" : "eligible"}">${esc(explanation)}</em></button>`; }).join("") : `<div class="communion-empty compact"><p>${query ? "No eligible communicants match this search." : "No eligible communicants are available for this service."}</p><small>Eligible adults must be marked Communicant in their member profile before they can be selected.</small></div>`;
  }

  function selectMember(memberId) {
    const form = $("#communionParticipantForm"); const member = state.members.find(item => item.id === memberId); const occasion = state.occasions.find(item => item.id === form.elements.occasion_id.value); if (!member || !occasion) return;
    const eligibility = memberEligibility(member, occasion.communion_date); if (!eligibility.eligible) return formError("#communionParticipantError", eligibility.reason);
    form.elements.member_id.value = member.id; $("#communionMemberResults").hidden = true; $("#communionSelectedMember").hidden = false; $("#communionSelectedMember").innerHTML = `<span><i data-lucide="badge-check"></i><strong>${esc(fullName(member))}</strong><small>${esc(eligibility.groupName)} · Communicant</small></span><button type="button" data-communion-change-member>Change</button>`; updateParticipantConditionalFields(); refreshIcons();
  }

  function updateParticipantConditionalFields() {
    const form = $("#communionParticipantForm"); if (!form) return; const visitor = form.elements.person_type.value === "Visitor"; const partook = form.elements.partook.checked;
    $("#communionMemberPicker").hidden = visitor; $("#communionVisitorFields").hidden = !visitor; form.elements.visitor_name.required = visitor; form.elements.visitor_gender.required = visitor; form.elements.visitor_communicant_status.required = visitor;
    const preview = $("#communionEligibilityPreview");
    if (visitor) { const status = form.elements.visitor_communicant_status.value; const eligible = status === "Communicant"; preview.className = `full communion-eligibility-preview ${eligible ? "eligible" : "ineligible"}`; preview.innerHTML = `<i data-lucide="${eligible ? "badge-check" : "circle-alert"}"></i><span><strong>${eligible ? "Eligible visitor / non-member" : "Not eligible to partake"}</strong><small>${eligible ? "Communicant eligibility is recorded for this occasion." : `${status} visitors cannot be marked as having partaken.`}</small></span>`; }
    else { const member = state.members.find(item => item.id === form.elements.member_id.value); const occasion = state.occasions.find(item => item.id === form.elements.occasion_id.value); const existing = state.participants.find(item => item.id === state.editingParticipantId); const eligibility = member && occasion ? memberEligibility(member, occasion.communion_date) : null; preview.className = `full communion-eligibility-preview ${(existing?.communicant_status === "Communicant" || eligibility?.eligible) ? "eligible" : "neutral"}`; preview.innerHTML = existing ? `<i data-lucide="history"></i><span><strong>Historical eligibility snapshot</strong><small>${esc(`${existing.generational_group_snapshot} · ${existing.communicant_status}`)}</small></span>` : eligibility ? `<i data-lucide="badge-check"></i><span><strong>${esc(eligibility.eligible ? "Eligible Communicant" : "Member not eligible")}</strong><small>${esc(eligibility.eligible ? `${eligibility.groupName} · Communicant` : eligibility.reason)}</small></span>` : `<i data-lucide="search"></i><span><strong>Select an eligible member</strong><small>Children Service, Junior Youth (JY), and Non-Communicants cannot be selected.</small></span>`; }
    if (partook && visitor && form.elements.visitor_communicant_status.value !== "Communicant") preview.classList.add("ineligible");
    const submit = $("#communionParticipantSubmit"); if (submit) submit.textContent = state.editingParticipantId ? "Save changes" : partook ? "Record as Partaken" : "Save register entry";
    refreshIcons();
  }

  function openParticipant(personType = "Member", record = null) {
    if (!can("communion.manage")) return notify("You do not have permission to manage the Communion Register.", "error"); const occasion = state.occasions.find(item => item.id === state.selectedOccasionId); if (!occasion) return;
    const form = $("#communionParticipantForm"); form.reset(); formError("#communionParticipantError"); state.editingParticipantId = record?.id || null; form.elements.participant_id.value = record?.id || ""; form.elements.occasion_id.value = occasion.id; form.elements.person_type.value = record?.person_type || personType; form.elements.member_id.value = record?.member_id || ""; form.elements.visitor_name.value = record?.visitor_name || ""; form.elements.visitor_gender.value = record?.gender_snapshot || "Female"; form.elements.visitor_communicant_status.value = record?.communicant_status || "Communicant"; form.elements.partook.checked = record ? record.partook : true; form.elements.notes.value = record?.notes || "";
    $("#communionMemberSearch").value = ""; $("#communionMemberResults").hidden = false; $("#communionSelectedMember").hidden = true; form.elements.person_type.disabled = Boolean(record);
    if (record?.person_type === "Member") { const member = state.members.find(item => item.id === record.member_id); $("#communionMemberResults").hidden = true; $("#communionSelectedMember").hidden = false; $("#communionSelectedMember").innerHTML = `<span><i data-lucide="history"></i><strong>${esc(fullName(member))}</strong><small>${esc(record.generational_group_snapshot)} · ${esc(record.communicant_status)} at this occasion</small></span>`; } else renderMemberResults();
    $("#communionParticipantDialogTitle").textContent = record ? "Edit Communion Register Entry" : `Add ${personType === "Visitor" ? "Eligible Visitor" : "Member"}`; updateParticipantConditionalFields(); $("#communionParticipantDialog").showModal(); refreshIcons();
  }

  async function saveOccasion(event) {
    event.preventDefault(); formError("#communionOccasionError"); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); if (values.communion_date > todayIso()) return formError("#communionOccasionError", "Communion date cannot be in the future.");
    const payload = { communion_date: values.communion_date, service_name: values.service_name.trim(), event_id: values.event_id || null, location: values.location.trim(), presiding_minister: values.presiding_minister.trim(), notes: values.notes.trim() };
    let savedOccasionId = values.occasion_id;
    if (savedOccasionId) {
      const { error } = await state.client.from("communion_occasions").update(payload).eq("id", savedOccasionId);
      if (error) return formError("#communionOccasionError", error.message);
    } else {
      const { data, error } = await state.client.from("communion_occasions").insert(payload).select("id").single();
      if (error) return formError("#communionOccasionError", error.message);
      savedOccasionId = data?.id;
    }
    $("#communionOccasionDialog").close();
    notify(values.occasion_id ? "Communion occasion updated." : "Communion occasion created. You can now record who partook.");
    await load();
    if (!values.occasion_id && savedOccasionId) openRegister(savedOccasionId);
  }

  async function saveParticipant(event) {
    event.preventDefault(); formError("#communionParticipantError"); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); if (form.elements.person_type.disabled) values.person_type = form.elements.person_type.value; const partook = form.elements.partook.checked; const visitor = values.person_type === "Visitor"; const occasion = state.occasions.find(item => item.id === values.occasion_id); let payload;
    if (visitor) { const status = values.visitor_communicant_status; const visitorName = values.visitor_name.trim().replace(/\s+/g, " "); if (!visitorName) return formError("#communionParticipantError", "Enter the visitor or non-member full name."); if (state.participants.some(item => item.occasion_id === occasion.id && item.person_type === "Visitor" && normalizedPersonName(item.visitor_name) === normalizedPersonName(visitorName) && item.id !== state.editingParticipantId)) return formError("#communionParticipantError", "This visitor or non-member is already recorded for this Communion service."); if (partook && status !== "Communicant") return formError("#communionParticipantError", "A visitor or non-member must be an eligible Communicant to partake."); payload = { occasion_id: occasion.id, person_type: "Visitor", member_id: null, visitor_name: visitorName, communicant_status: status, partook, gender_snapshot: values.visitor_gender, generational_group_snapshot: "Visitor / Non-Member", notes: values.notes.trim() }; }
    else { const member = state.members.find(item => item.id === values.member_id); if (!member) return formError("#communionParticipantError", "Select an eligible registered member."); if (state.participants.some(item => item.occasion_id === occasion.id && item.member_id === member.id && item.id !== state.editingParticipantId)) return formError("#communionParticipantError", "This member is already recorded for this Communion service."); const existing = state.participants.find(item => item.id === state.editingParticipantId); const eligibility = memberEligibility(member, occasion.communion_date); if ((!existing || !existing.partook) && partook && !eligibility.eligible) return formError("#communionParticipantError", eligibility.reason); if (existing && partook && existing.communicant_status !== "Communicant") return formError("#communionParticipantError", "This historical register entry is Non-Communicant and cannot be marked as having partaken."); payload = { occasion_id: occasion.id, person_type: "Member", member_id: member.id, visitor_name: null, communicant_status: existing?.communicant_status || member.communicant_status || "Non-Communicant", partook, gender_snapshot: existing?.gender_snapshot || member.gender, generational_group_snapshot: existing?.generational_group_snapshot || eligibility.groupName, notes: values.notes.trim() }; }
    const query = state.editingParticipantId ? state.client.from("communion_participants").update(payload).eq("id", state.editingParticipantId) : state.client.from("communion_participants").insert(payload); const { error } = await query; if (error) return formError("#communionParticipantError", error.code === "23505" ? "This person already has a register entry for this Communion occasion." : error.message); $("#communionParticipantDialog").close(); state.editingParticipantId = null; notify("Communion Register entry saved."); await load();
  }

  async function removeRecord(table, id, label) { if (!can("communion.manage") || !confirm(`Delete this ${label}?${table === "communion_occasions" ? " Its Communion Register will also be deleted." : ""} This cannot be undone.`)) return; const { error } = await state.client.from(table).delete().eq("id", id); if (error) return notify(error.message, "error"); notify(`${label[0].toUpperCase() + label.slice(1)} deleted.`); await load(); }

  async function load() {
    if (!state.client || !can("communion.view")) return; state.loading = true; render(); const [occasions, participants] = await Promise.all([state.client.from("communion_occasions").select("*,events(id,title,event_date,location)").order("communion_date", { ascending: false }), state.client.from("communion_participants").select("*,members(id,first_name,last_name,date_of_birth,gender,phone,email,group_name,status,communicant_status)").order("created_at", { ascending: true })]); state.loading = false; const failure = occasions.error || participants.error; if (failure) { $("#communionMessage").hidden = false; $("#communionMessage").textContent = `Unable to load Communion records. Confirm the latest database migration has been applied. ${failure.message}`; render(); return; } $("#communionMessage").hidden = true; state.occasions = occasions.data || []; state.participants = participants.data || []; render();
  }

  function memberHistoryMarkup(memberId) {
    if (!can("communion.view")) return ""; const records = state.participants.filter(item => item.member_id === memberId).map(item => ({ ...item, occasion: state.occasions.find(occasion => occasion.id === item.occasion_id) })).filter(item => item.occasion).sort((a, b) => b.occasion.communion_date.localeCompare(a.occasion.communion_date)); const partook = records.filter(item => item.partook); const last = partook[0];
    return `<section class="member-communion-section"><div class="member-communion-heading"><div><p class="eyebrow">CHURCH RECORD</p><h4>Communion History</h4><p>Only explicit Communion Register entries are shown; missing records are not interpreted.</p></div></div><div class="member-communion-summary"><div><span>Total recorded participations</span><strong>${partook.length}</strong></div><div><span>Last recorded participation</span><strong>${last ? formatDate(last.occasion.communion_date) : "None"}</strong></div></div><div class="table-scroll"><table class="member-communion-table"><thead><tr><th>Date</th><th>Occasion</th><th>Group at occasion</th><th>Partook</th></tr></thead><tbody>${records.length ? records.map(item => `<tr><td>${formatDate(item.occasion.communion_date)}</td><td><button class="communion-link" type="button" data-member-communion-occasion="${item.occasion.id}">${esc(item.occasion.service_name)}</button></td><td>${esc(item.generational_group_snapshot)}</td><td><span class="communion-partook ${item.partook ? "yes" : "no"}">${item.partook ? "Partook" : "Did not partake"}</span></td></tr>`).join("") : `<tr><td colspan="4"><div class="communion-empty compact"><p>No explicit Communion Register entries for this member.</p></div></td></tr>`}</tbody></table></div></section>`;
  }

  function bindEvents() {
    if (state.bound) return; state.bound = true; $("#communionPrimaryAction").addEventListener("click", () => openOccasion()); $("#communionOccasionForm").addEventListener("submit", saveOccasion); $("#communionParticipantForm").addEventListener("submit", saveParticipant);
    document.addEventListener("click", event => { const close = event.target.closest("[data-close-communion]")?.dataset.closeCommunion; if (close) $("#" + close)?.close(); if (event.target.closest("[data-communion-open-occasion]")) openOccasion(); const register = event.target.closest("[data-communion-register]")?.dataset.communionRegister; if (register) { state.selectedOccasionId = register; state.registerSearch = ""; state.rosterSearch = ""; render(); } if (event.target.closest("[data-communion-dashboard]")) { state.selectedOccasionId = null; state.registerSearch = ""; state.rosterSearch = ""; render(); } const editOccasion = event.target.closest("[data-communion-edit-occasion]")?.dataset.communionEditOccasion; if (editOccasion) openOccasion(state.occasions.find(item => item.id === editOccasion)); const deleteOccasion = event.target.closest("[data-communion-delete-occasion]")?.dataset.communionDeleteOccasion; if (deleteOccasion) removeRecord("communion_occasions", deleteOccasion, "Communion occasion"); const addType = event.target.closest("[data-communion-add]")?.dataset.communionAdd; if (addType) openParticipant(addType); const recordMember = event.target.closest("[data-communion-record-member]")?.dataset.communionRecordMember; if (recordMember) { openParticipant("Member"); selectMember(recordMember); } const select = event.target.closest("[data-communion-select-member]")?.dataset.communionSelectMember; if (select) selectMember(select); if (event.target.closest("[data-communion-change-member]")) { const form = $("#communionParticipantForm"); form.elements.member_id.value = ""; $("#communionSelectedMember").hidden = true; $("#communionMemberResults").hidden = false; renderMemberResults($("#communionMemberSearch").value); updateParticipantConditionalFields(); } const editParticipant = event.target.closest("[data-communion-edit-participant]")?.dataset.communionEditParticipant; if (editParticipant) openParticipant("Member", state.participants.find(item => item.id === editParticipant)); const deleteParticipant = event.target.closest("[data-communion-delete-participant]")?.dataset.communionDeleteParticipant; if (deleteParticipant) removeRecord("communion_participants", deleteParticipant, "register entry"); });
    document.addEventListener("input", event => { if (event.target.id === "communionMemberSearch") renderMemberResults(event.target.value); if (event.target.id === "communionRosterSearch") { state.rosterSearch = event.target.value; render(); const input = $("#communionRosterSearch"); input?.focus(); input?.setSelectionRange(input.value.length, input.value.length); } if (event.target.id === "communionRegisterSearch") { state.registerSearch = event.target.value; render(); const input = $("#communionRegisterSearch"); input?.focus(); input?.setSelectionRange(input.value.length, input.value.length); } if (event.target.closest("#communionParticipantForm") && ["person_type", "visitor_communicant_status", "partook"].includes(event.target.name)) updateParticipantConditionalFields(); });
    document.addEventListener("change", event => { if (event.target.closest("#communionParticipantForm") && ["person_type", "visitor_communicant_status", "partook"].includes(event.target.name)) updateParticipantConditionalFields(); if (event.target.matches('#communionOccasionForm [name="event_id"]') && event.target.value) { const selected = state.events.find(item => item.id === event.target.value); const form = $("#communionOccasionForm"); if (selected) { form.elements.communion_date.value = selected.event_date; form.elements.service_name.value = selected.title; form.elements.location.value = selected.location || form.elements.location.value; } } });
  }

  async function initialize(context) { state.client = context.client; state.userId = context.userId; state.permissions = context.permissions || []; state.members = context.members || []; state.events = context.events || []; state.initialized = true; bindEvents(); await load(); }
  function syncReferenceData(members, events) { state.members = members || []; state.events = events || []; }
  function openRegister(occasionId) { if (!can("communion.view") || !state.occasions.some(item => item.id === occasionId)) return; state.selectedOccasionId = occasionId; state.registerSearch = ""; state.rosterSearch = ""; render(); }

  mount();
  window.CommunionModule = { initialize, load, render, openOccasion, openRegister, syncReferenceData, memberEligibility, memberHistoryMarkup, communionStats, statsFor, getData: () => ({ occasions: state.occasions.slice(), participants: state.participants.slice() }) };
})();
